version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      action-deps:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/.devcontainer"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
