FROM mcr.microsoft.com/devcontainers/go:dev-1.26-trixie

USER root
RUN apt-get update \
    && apt-get -y install --no-install-recommends iproute2 procps \
    && rm -rf /var/lib/apt/lists/*

USER vscode